In [1]:
import pandas as pd
import os
import numpy as np
import csv

In [2]:
df = pd.DataFrame()

df = pd.read_csv("tokenized_data.csv")
df.head()

Tokenized  Truth
0  ['alex', 'jones', 'vindicated', 'in', 'pizzaga...      0
1  ['the', 'big', 'data', 'conspiracy', 'governme...      0
2  ['california', 'surprisingly', 'lenient', 'on'...      0
3  ['mexicans', 'are', 'chomping', 'at', 'the', '...      0
4  ['breaking', 'news', 'snapchat', 'to', 'purcha...      0

In [3]:
import pickle

nrc_lexicon = pickle.load(open('nrc.pkl', 'rb'))

In [4]:
for index, row in df.iterrows():
    line = row[0]
    line = row[0].split(',')
    
    length = len(line)
    
    vec = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    org_vector = np.asarray(vec)
    number_found = 0
    
    for word in line:
        if word.strip(" ' ") in nrc_lexicon:
            word_vector = np.asarray(nrc_lexicon[word.strip(" ' ")])
            number_found += 1
            org_vector = (org_vector + word_vector)
            
    org_vector = (org_vector/number_found) * 1000
    
    df.at[index, 'anger'] = org_vector[0]
    df.at[index, 'anticipation'] = org_vector[1]
    df.at[index, 'disgust'] = org_vector[2]
    df.at[index, 'fear'] = org_vector[3]
    df.at[index, 'joy'] = org_vector[4]
    df.at[index, 'sadness'] = org_vector[5]
    df.at[index, 'surprise'] = org_vector[6]
    df.at[index, 'trust'] = org_vector[7]
    df.at[index, 'positive'] = org_vector[8]
    df.at[index, 'negative'] = org_vector[9]

In [5]:
df

Tokenized  Truth       anger  \
0    ['alex', 'jones', 'vindicated', 'in', 'pizzaga...      0    0.000000   
1    ['the', 'big', 'data', 'conspiracy', 'governme...      0    0.000000   
2    ['california', 'surprisingly', 'lenient', 'on'...      0    0.000000   
3    ['mexicans', 'are', 'chomping', 'at', 'the', '...      0    0.000000   
4    ['breaking', 'news', 'snapchat', 'to', 'purcha...      0    0.000000   
5    ['brexit', 'talks', 'are', 'seeing', 'success'...      0    0.000000   
6    ['robots', 'taking', 'over', 'the', 'world', '...      0    0.000000   
7    ['brewdog', 'under', 'fire', 'for', 'accusatio...      0   31.250000   
8    ['tesco', 'will', 'not', 'pay', 'out', 'any', ...      0    0.000000   
9    ['uber', 'to', 'open', 'new', 'headquarters', ...      0    0.000000   
10   ['eu', 'applauds', 'deutsche', 'boerses', '14'...      0    0.000000   
11   ['toshibas', 'westinghouse', 'creating', 'thri...      0    0.000000   
12   ['ford', 'has', 'been', 'forced', 'by', 'donal...      0    0.000000   
13   ['amazon', 'to', 'sell', 'middle', 'east', 'on...      0    0.000000   
14   ['wells', 'fargo', 'profits', 'spike', 'despit...      0    0.000000   
15   ['elon', 'musk', 'the', 'brains', 'behind', 't...      0    0.000000   
16   ['uk', 'banks', 'said', 'not', 'prepared', 'fo...      0    0.000000   
17   ['an', 'increase', 'in', 'shorthaul', 'airline...      0    0.000000   
18   ['britain', 'retailers', 'can', 'not', 'seem',...      0    0.000000   
19   ['chief', 'executive', 'alexandre', 'de', 'jun...      0    0.000000   
20   ['american', 'airlines', 'gets', 'old', 'plane...      0    0.000000   
21   ['london', 'stock', 'exchangedeutsche', 'boers...      0   25.641026   
22   ['chinas', 'tencent', 'begins', 'slow', 'takeo...      0    0.000000   
23   ['london', 'stock', 'exchange', 'has', 'droppe...      0    0.000000   
24   ['german', 'power', 'spat', 'with', 'denmark',...      0    0.000000   
25   ['dan', 'moss', 'and', 'scott', 'lanman', 'gol...      0    0.000000   
26   ['briton', 'stock', 'market', 'takes', 'plunge...      0    0.000000   
27   ['macron', 'and', 'le', 'pen', 'fight', 'for',...      0    0.000000   
28   ['the', 'price', 'of', 'gold', 'fell', 'today'...      0    0.000000   
29   ['energy', 'minister', 'alexander', 'novak', '...      0    0.000000   
..                                                 ...    ...         ...   
450  ['google', 'maps', 'can', 'tell', 'your', 'fri...      1    0.000000   
451  ['fossil', 'has', 'a', 'ton', 'of', 'new', 'sm...      1    0.000000   
452  ['amazons', 'alexa', 'adds', 'prime', 'now', '...      1    0.000000   
453  ['the', 'oldest', 'vespa', 'in', 'existence', ...      1    0.000000   
454  ['let', 'there', 'be', 'light', 'german', 'sci...      1    0.000000   
455  ['no', 'new', 'threat', 'led', 'to', 'airline'...      1    0.000000   
456  ['apple', 'cuts', 'prices', 'on', 'lowerend', ...      1    0.000000   
457  ['ban', 'aimed', 'at', 'electronics', 'in', 'c...      1    0.000000   
458  ['yahoo', 'reveals', 'massive', 'breach', 'of'...      1    0.000000   
459  ['phone', 'device', 'tests', 'male', 'fertilit...      1    0.000000   
460  ['wells', 'fargo', 'introduces', 'cardless', '...      1    0.000000   
461  ['gps', 'device', 'to', 'prevent', 'false', 'e...      1    0.000000   
462  ['following', 'youtube', 'gaffe', 'att', 'veri...      1    0.000000   
463  ['toyota', 'teams', 'up', 'with', 'microsoft',...      1    0.000000   
464  ['amazon', 'prime', 'air', 'drone', 'completes...      1    0.000000   
465  ['amazon', 'has', 'more', 'budget', 'phones', ...      1    0.000000   
466  ['youtube', 'reverses', 'some', 'restrictions'...      1    0.000000   
467  ['google', 'allows', 'users', 'to', 'share', '...      1    0.000000   
468  ['fruitshaped', 'sensor', 'can', 'improve', 'f...      1    0.000000   
469  ['twitter', 'adds', 'more', 'antiabuse', 'tool...      1    0.000000   
470  ['instagram', 'adds', 'twofactor', '

In [6]:
df = df[['Tokenized','anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 'trust', 'positive', 'negative', 'Truth']]

In [7]:
df.to_csv('scored_data.csv', index=False)

In [8]:
new_df = pd.read_csv('scored_data.csv')

In [9]:
X = new_df.drop(['Tokenized', 'Truth'], axis = 1)
y = new_df['Truth']

In [10]:
X

anger  anticipation  disgust       fear  joy     sadness  \
0      0.000000     33.898305      0.0  16.949153  0.0   16.949153   
1      0.000000      0.000000      0.0  38.461538  0.0    0.000000   
2      0.000000     41.666667      0.0   0.000000  0.0    0.000000   
3      0.000000      0.000000      0.0   0.000000  0.0   32.258065   
4      0.000000     68.965517      0.0   0.000000  0.0   68.965517   
5      0.000000     66.666667      0.0  66.666667  0.0    0.000000   
6      0.000000     58.823529      0.0  29.411765  0.0   88.235294   
7     31.250000     93.750000      0.0  31.250000  0.0    0.000000   
8      0.000000     31.250000      0.0  31.250000  0.0    0.000000   
9      0.000000     68.965517      0.0  34.482759  0.0   34.482759   
10     0.000000     20.000000      0.0  20.000000  0.0    0.000000   
11     0.000000      0.000000      0.0   0.000000  0.0   41.666667   
12     0.000000      0.000000      0.0   0.000000  0.0   83.333333   
13     0.000000     34.482759      0.0   0.000000  0.0    0.000000   
14     0.000000      0.000000      0.0  76.923077  0.0    0.000000   
15     0.000000      0.000000      0.0   0.000000  0.0   66.666667   
16     0.000000     25.641026      0.0   0.000000  0.0   51.282051   
17     0.000000      0.000000      0.0   0.000000  0.0    0.000000   
18     0.000000     58.823529      0.0   0.000000  0.0    0.000000   
19     0.000000     30.303030      0.0  30.303030  0.0   30.303030   
20     0.000000      0.000000      0.0   0.000000  0.0    0.000000   
21    25.641026      0.000000      0.0   0.000000  0.0   25.641026   
22     0.000000     74.074074      0.0   0.000000  0.0    0.000000   
23     0.000000     34.482759      0.0   0.000000  0.0    0.000000   
24     0.000000      0.000000      0.0   0.000000  0.0    0.000000   
25     0.000000     27.027027      0.0   0.000000  0.0   27.027027   
26     0.000000    103.448276      0.0   0.000000  0.0  103.448276   
27     0.000000      0.000000      0.0   0.000000  0.0   37.037037   
28     0.000000     55.555556      0.0   0.000000  0.0   83.333333   
29     0.000000     34.482759      0.0   0.000000  0.0    0.000000   
..          ...           ...      ...        ...  ...         ...   
450    0.000000     37.037037      0.0  37.037037  0.0   74.074074   
451    0.000000     66.666667      0.0  33.333333  0.0    0.000000   
452    0.000000     38.461538      0.0   0.000000  0.0    0.000000   
453    0.000000    312.500000      0.0   0.000000  0.0    0.000000   
454    0.000000     55.555556      0.0  55.555556  0.0    0.000000   
455    0.000000     41.666667      0.0   0.000000  0.0   83.333333   
456    0.000000      0.000000      0.0   0.000000  0.0   66.666667   
457    0.000000     45.454545      0.0   0.000000  0.0    0.000000   
458    0.000000     32.258065      0.0   0.000000  0.0    0.000000   
459    0.000000      0.000000      0.0  37.037037  0.0   37.037037   
460    0.000000      0.000000      0.0   0.000000  0.0   47.619048   
461    0.000000     64.516129      0.0  64.516129  0.0    0.000000   
462    0.000000      0.000000      0.0   0.000000  0.0  153.846154   
463    0.000000      0.000000      0.0   0.000000  0.0    0.000000   
464    0.000000      0.000000      0.0   0.000000  0.0    0.000000   
465    0.000000      0.000000      0.0   0.000000  0.0    0.000000   
466    0.000000      0.000000      0.0   0.000000  0.0  200.000000   
467    0.000000     55.555556      0.0  27.777778  0.0    0.000000   
468    0.000000      0.000000      0.0   0.000000  0.0    0.000000   
469    0.000000      0.000000      0.0   0.000000  0.0   95.238095   
470    0.000000     62.500000      0.0   0.000000  0.0    0.000000   
471    0.000000     40.000000      0.0  40.000000  0.0    0.000000   
472  138.888889      0.000000      0.0  27.777778  0.0    0.000000   
473    0.000000     38.461538      0.0   0.000000  0.0   38.461538   
474    0.000000     35.714286      0.0  35.714286  0.0    0.000000   
475    0.000000     

In [15]:
np.random.RandomState(50)

from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)  

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()

# scaler.fit(X_train)

In [ ]:
# X_train = scaler.transform(X_train)
# X_test = scaler.transform(X_test)

In [17]:
from sklearn.svm import SVC  
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [18]:
y_pred = svclassifier.predict(X_test)  

In [19]:
print(y_pred)
print()
print(np.asarray(y_test))

[0 0 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 0 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1
 0 1 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1 1 1 0 1 0]

[1 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 1
 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0
 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 0 1]


In [20]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[16 29]
 [28 23]]
              precision    recall  f1-score   support

           0       0.36      0.36      0.36        45
           1       0.44      0.45      0.45        51

   micro avg       0.41      0.41      0.41        96
   macro avg       0.40      0.40      0.40        96
weighted avg       0.41      0.41      0.41        96



# Other Models

In [21]:
from sklearn.naive_bayes import GaussianNB
NBclassifier = GaussianNB()
NBclassifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
pred = NBclassifier.predict(X_test)

In [ ]:
print(pred)
print()
print(np.asarray(y_test))

In [23]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, pred))  
print(classification_report(y_test, pred))  

[[ 5 40]
 [ 5 46]]
              precision    recall  f1-score   support

           0       0.50      0.11      0.18        45
           1       0.53      0.90      0.67        51

   micro avg       0.53      0.53      0.53        96
   macro avg       0.52      0.51      0.43        96
weighted avg       0.52      0.53      0.44        96



In [24]:
from sklearn.naive_bayes import MultinomialNB
MNBclassifier = MultinomialNB()
MNBclassifier.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [25]:
MNB_pred = MNBclassifier.predict(X_test)

In [ ]:
print(MNB_pred)
print(np.asarray(y_test))

In [26]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, MNB_pred))  
print(classification_report(y_test, MNB_pred))  

[[18 27]
 [25 26]]
              precision    recall  f1-score   support

           0       0.42      0.40      0.41        45
           1       0.49      0.51      0.50        51

   micro avg       0.46      0.46      0.46        96
   macro avg       0.45      0.45      0.45        96
weighted avg       0.46      0.46      0.46        96



In [27]:
from sklearn.neighbors import KNeighborsClassifier
KNNclassifier = KNeighborsClassifier()
KNNclassifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [28]:
KNN_pred = KNNclassifier.predict(X_test)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, KNN_pred))  
print(classification_report(y_test, KNN_pred))  

[[27 18]
 [30 21]]
              precision    recall  f1-score   support

           0       0.47      0.60      0.53        45
           1       0.54      0.41      0.47        51

   micro avg       0.50      0.50      0.50        96
   macro avg       0.51      0.51      0.50        96
weighted avg       0.51      0.50      0.50        96



In [30]:
from sklearn.neural_network import MLPClassifier

In [31]:
mlp = MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [32]:
mlp.fit(X_train,y_train)

/Users/anshumannandy/Desktop/AnacondaFolder/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [33]:
predictions = mlp.predict(X_test)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  

[[21 24]
 [32 19]]
              precision    recall  f1-score   support

           0       0.40      0.47      0.43        45
           1       0.44      0.37      0.40        51

   micro avg       0.42      0.42      0.42        96
   macro avg       0.42      0.42      0.42        96
weighted avg       0.42      0.42      0.42        96

